apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: digi
  name: spring-boot-demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo-pod
  template:
    metadata:
      annotations:
        ad.datadoghq.com/app.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:%%port%%/actuator/prometheus",
                  "namespace": "alero",
                  "metrics": ["http_*"]
                }
              ]
            }
          }
      labels:
        app: spring-boot-demo-pod
    spec:
      containers:
      - name: app
        image: yoavklein3/spring-boot-app:0.1
        ports:
          - name: main
            containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  namespace: digi
  name: spring-boot-demo-svc
spec:
  type: ClusterIP
  selector:
    app: spring-boot-demo-pod
  ports:
  - name: main
    port: 80
    targetPort: 8082
