/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

@RestController
@SpringBootApplication
public class MyApplication {

    RestTemplate restTemplate = new RestTemplate();
	
    @RequestMapping("/")
	String home() {
        try {
            // a call to google, just to see it in the UI
            ResponseEntity<String> response = restTemplate.getForEntity("https://google.com", String.class);
            response = restTemplate.getForEntity("http://backend", String.class);
            System.out.println("Status Code: " + response.getStatusCode());
            System.out.println("Response Body: " + response.getBody());
            return response.getBody();
        } catch(Exception e) {
            return "Exception";
        }

	}

	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}


