/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;


public class RestClientExample {
    public static void main(String[] args) throws InterruptedException {
        RestTemplate restTemplate = new RestTemplate();

        // Example: GET request to a public API
        String url = System.getenv("SERVER_ENDPOINT");

        System.out.println("=== URL: " + url);
        
        Thread.sleep(3000);
        while(true) {
            try {
                ResponseEntity<String> response = restTemplate.getForEntity(url, String.class);
                System.out.println("Status Code: " + response.getStatusCode());
                System.out.println("Response Body: " + response.getBody());        
            } catch(Exception e) {
                System.out.println("Connect exception");
            }
            Thread.sleep(2000);
        }
    }
}
